server:
  port: 8081
spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    password: Akhil@2020
    url: jdbc:mysql://localhost:3306/ecommercedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      cors:
        exposed-headers: '*'
auth-service:
 messages:
  userReg: User Created
  userRegErr: User Creation Failed
  login: Login Success
  loginErr: Invalid Credentials
  

 
