
spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    password: Akhil@2020
    url: jdbc:mysql://localhost:3306/akhilreddydb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      cors:
        exposed-headers: '*'
        
  server:
    port: 8081

 
