server:
  port: 8081
spring:
  datasource:
    password: Akhil@2020
    url: jdbc:mysql://localhost:3306/akhilreddydb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
